# Generated by scripts/homebrew/formula.mjs in https://github.com/EvanZhang008/open-walnut for open-walnut 0.6.7.
class OpenWalnut < Formula
  desc "Personal AI: tasks, notes and Claude Code sessions on your own machine"
  homepage "https://github.com/EvanZhang008/open-walnut"
  version "0.6.7"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/EvanZhang008/open-walnut/releases/download/v0.6.7/open-walnut-0.6.7-darwin-arm64.tar.gz", using: :nounzip
      sha256 "212055a94644edc4293def4f0cc9acf30e377a8f872b18d22373015de936839c"
    end
    on_intel do
      url "https://github.com/EvanZhang008/open-walnut/releases/download/v0.6.7/open-walnut-0.6.7-darwin-x64.tar.gz", using: :nounzip
      sha256 "6f40f89dc18142ca4b25b85143028029d041adc608d9cf9cdb29d335c3d73f40"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/EvanZhang008/open-walnut/releases/download/v0.6.7/open-walnut-0.6.7-linux-arm64.tar.gz", using: :nounzip
      sha256 "29e5bd685b03759f0883245506c91db3d5f58924d826b2b25ffdfbdfa79bce73"
    end
    on_intel do
      url "https://github.com/EvanZhang008/open-walnut/releases/download/v0.6.7/open-walnut-0.6.7-linux-x64.tar.gz", using: :nounzip
      sha256 "0f3748fe44f19a3aa8e23f4bdf98d0880c1732564e19aa8275a708ef841b1b1f"
    end
  end

  def install
    libexec.install Dir["open-walnut-*.tar.gz"].first => "open-walnut.tar.gz"
    # Scripts, not links: the cleaner drops a link whose target is not there yet.
    bin.write_exec_script libexec/"app/bin/walnut", libexec/"app/bin/open-walnut"
  end

  # After Homebrew's install-name pass over the keg, which the archive must skip.
  # The packed copy goes once unpacked, so running these again changes nothing.
  post_install_steps do
    if_path_exists "open-walnut.tar.gz", base: :libexec do
      remove "app", base: :libexec, recursive: true
      mkdir_p "app", base: :libexec
      run "tar", args: ["-xzf", "{{libexec}}/open-walnut.tar.gz", "-C", "{{libexec}}/app", "--strip-components=1"],
                 writable_paths: ["app"], writable_base: :libexec
      remove "open-walnut.tar.gz", base: :libexec
    end
  end

  def caveats
    <<~EOS
      Start it with:
        walnut web
      Walnut keeps itself up to date: it installs new releases when it starts.
      Its sessions run Claude Code: https://claude.com/product/claude-code
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/walnut --version")
  end
end
