# Generated by scripts/homebrew/formula.mjs in https://github.com/EvanZhang008/open-walnut for open-walnut 0.6.5.
class OpenWalnut < Formula
  desc "Personal AI: tasks, notes and Claude Code sessions on your own machine"
  homepage "https://github.com/EvanZhang008/open-walnut"
  version "0.6.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/EvanZhang008/open-walnut/releases/download/v0.6.5/open-walnut-0.6.5-darwin-arm64.tar.gz", using: :nounzip
      sha256 "a33e50eb0a37de4e2a134354828e8026d59a0d162866487556979f5e6ed23069"
    end
    on_intel do
      url "https://github.com/EvanZhang008/open-walnut/releases/download/v0.6.5/open-walnut-0.6.5-darwin-x64.tar.gz", using: :nounzip
      sha256 "2629275bf0b740e526b2289f2faacbaa7aed47fa926abe729aaf324cd0f3c815"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/EvanZhang008/open-walnut/releases/download/v0.6.5/open-walnut-0.6.5-linux-arm64.tar.gz", using: :nounzip
      sha256 "f1f15c4c20bcb2b53ec395b586228e54ba8c94ae1cb173cd3ea6aa7e07b8c3f9"
    end
    on_intel do
      url "https://github.com/EvanZhang008/open-walnut/releases/download/v0.6.5/open-walnut-0.6.5-linux-x64.tar.gz", using: :nounzip
      sha256 "0f5b8dc4f0f143b71abf45b1d2be6d96844e50d0aa1898f7da0081b8f597ce34"
    end
  end

  def install
    libexec.install Dir["open-walnut-*.tar.gz"].first => "open-walnut.tar.gz"
    # Scripts, not links: the cleaner drops a link whose target is not there yet.
    bin.write_exec_script libexec/"app/bin/walnut", libexec/"app/bin/open-walnut"
  end

  # After Homebrew's install-name pass over the keg, which the archive must skip.
  # The packed copy goes once unpacked, so running these again changes nothing.
  post_install_steps do
    if_path_exists "open-walnut.tar.gz", base: :libexec do
      remove "app", base: :libexec, recursive: true
      mkdir_p "app", base: :libexec
      run "tar", args: ["-xzf", "{{libexec}}/open-walnut.tar.gz", "-C", "{{libexec}}/app", "--strip-components=1"],
                 writable_paths: ["app"], writable_base: :libexec
      remove "open-walnut.tar.gz", base: :libexec
    end
  end

  def caveats
    <<~EOS
      Start it with:
        walnut web
      Walnut keeps itself up to date: it installs new releases when it starts.
      Its sessions run Claude Code: https://claude.com/product/claude-code
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/walnut --version")
  end
end
