# Generated by scripts/homebrew/formula.mjs in https://github.com/EvanZhang008/open-walnut for open-walnut 0.6.4.
class OpenWalnut < Formula
  desc "Personal AI: tasks, notes and Claude Code sessions on your own machine"
  homepage "https://github.com/EvanZhang008/open-walnut"
  version "0.6.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/EvanZhang008/open-walnut/releases/download/v0.6.4/open-walnut-0.6.4-darwin-arm64.tar.gz", using: :nounzip
      sha256 "7a2fd9592d87236af40c495ea70ddb9fa65aed1f78b625f0733a9d4f7550aef6"
    end
    on_intel do
      url "https://github.com/EvanZhang008/open-walnut/releases/download/v0.6.4/open-walnut-0.6.4-darwin-x64.tar.gz", using: :nounzip
      sha256 "04477738780f22be0f689abda610a3a82b9b35d6f665ad0491ebaa2d95fc42ed"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/EvanZhang008/open-walnut/releases/download/v0.6.4/open-walnut-0.6.4-linux-arm64.tar.gz", using: :nounzip
      sha256 "c2681d4d68e87009e3f118e390fb48afd0a900ccaaaa5164c819eaf81cd8f61d"
    end
    on_intel do
      url "https://github.com/EvanZhang008/open-walnut/releases/download/v0.6.4/open-walnut-0.6.4-linux-x64.tar.gz", using: :nounzip
      sha256 "67d9226da2ccb7365c4e7d9c5f452d0b92a1c5d72bce7b4516a2dff745a54238"
    end
  end

  def install
    libexec.install Dir["open-walnut-*.tar.gz"].first => "open-walnut.tar.gz"
    # Scripts, not links: the cleaner drops a link whose target is not there yet.
    bin.write_exec_script libexec/"app/bin/walnut", libexec/"app/bin/open-walnut"
  end

  # After Homebrew's install-name pass over the keg, which the archive must skip.
  # The packed copy goes once unpacked, so running these again changes nothing.
  post_install_steps do
    if_path_exists "open-walnut.tar.gz", base: :libexec do
      remove "app", base: :libexec, recursive: true
      mkdir_p "app", base: :libexec
      run "tar", args: ["-xzf", "{{libexec}}/open-walnut.tar.gz", "-C", "{{libexec}}/app", "--strip-components=1"],
                 writable_paths: ["app"], writable_base: :libexec
      remove "open-walnut.tar.gz", base: :libexec
    end
  end

  def caveats
    <<~EOS
      Start it with:
        walnut web
      Walnut keeps itself up to date: it installs new releases when it starts.
      Its sessions run Claude Code: https://claude.com/product/claude-code
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/walnut --version")
  end
end
